# Generated by Django 2.1.5 on 2019-02-08 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vanilla', 'Vanilla')], default='Chocolate', max_length=255)),
                ('available', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Seasonal', 'Seasonal')], default='Daily', max_length=20)),
                ('featured', models.BooleanField(default=True)),
                ('date_churned', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
